In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [14]:
%time
for _ in range(100):
    my_arr2 = my_arr*2

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 7.15 µs


In [10]:
%time for _ in range(100): my_list2 = [x*2 for x in my_list]

CPU times: user 8.64 s, sys: 1.71 s, total: 10.3 s
Wall time: 10.4 s


In [25]:
data = np.random.randn(3,3)

In [26]:
data

array([[-1.068594  , -2.5971957 , -1.37605626],
       [-2.3420594 ,  1.02520979,  1.27454331],
       [-0.73121827, -0.4618128 ,  0.35773414]])

In [27]:
%time
data*10

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.96 µs


array([[-10.68594001, -25.97195704, -13.76056262],
       [-23.420594  ,  10.2520979 ,  12.74543307],
       [ -7.31218265,  -4.618128  ,   3.57734145]])

In [28]:
data.shape

(3, 3)

In [29]:
data.dtype

dtype('float64')

In [40]:
data1=[1,'hello',3,4,5,6,7,8,9.0,0]

In [41]:
arr1 = np.array(data1)

In [43]:
arr1

array(['1', 'hello', '3', '4', '5', '6', '7', '8', '9.0', '0'],
      dtype='<U21')

In [44]:
arr1*2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [48]:
arr3=np.random.randn(3,3,3)

In [49]:
arr3

array([[[ 0.55822493,  0.43535259, -0.36669221],
        [-0.12474066, -0.38333032,  0.8586363 ],
        [ 0.07896237,  0.4754151 ,  1.9286522 ]],

       [[-0.83808455, -2.03429602,  0.39289894],
        [-0.45049811, -0.09173822, -0.46969914],
        [-0.43431946, -0.79741944, -1.80587717]],

       [[-1.11687077, -1.9582946 ,  2.41810895],
        [-0.54857607, -0.37426991, -0.50892673],
        [-0.42000686, -0.51288877, -0.83782438]]])

In [50]:
arr3.ndim

3

In [53]:
np.empty((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
arr2 = np.array([1,2,3,4,5], dtype=np.float64)

## 

In [58]:
arr2


array([1., 2., 3., 4., 5.])

In [59]:
arr3 = arr2.astype(np.int32)

In [60]:
arr3

array([1, 2, 3, 4, 5], dtype=int32)

In [61]:
!pwd


/Users/krishansingh/Untitled Folder
